version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/core"
      - "/framework"
      - "/transports"
      - "/plugins/*"
      - "/examples/**"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directories:
      - "/ui"
      - "/npx"
      - "/examples/**"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/transports"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
